name: novels
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.16
  image_picker: ^0.8.6
  fluttertoast: ^8.1.1
  flutter_rating_bar: ^4.0.1
  firebase_auth: ^4.1.5
  cloud_firestore: ^4.1.0
  url_launcher: ^6.1.7
  hexcolor: ^3.0.1
  smooth_page_indicator: ^1.0.0+2
  particles_flutter: ^0.1.4
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf

    - family: MyFont
      fonts:
        - asset: assets/fonts/font.ttf
          weight: 700
